version: '2.0'
services:
  <%-serviceName%>:
    build:
      context: .
      dockerfile: deploy/Dockerfile_dev
      args:
        - http_proxy
        - HTTP_PROXY
        - https_proxy
        - HTTPS_PROXY
        - no_proxy
        - NO_PROXY
    volumes:
    - .:/phovea
