version: 2
jobs:
  build:
    working_directory: ~/phovea
    docker:
      - image: circleci/node:6-browsers
    tags:
      - /v\d+.\d+.\d+.*/
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
          - ./node_modules
      - run:
          name: dist
          command: npm run test
