version: 2
jobs:
  build:
    working_directory: ~/phovea
    docker:
      - image: circleci/node:12-browsers
    tags:
      - /v\d+.\d+.\d+.*/
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
          - ./node_modules
      - run:
          name: dist
          command: npm run test
workflows:
  version: 2
#  build-nightly:
#    triggers:
#      - schedule:
#          cron: "15 1 * * 1-5" # "At 01:15 on every day-of-week from Monday through Friday.”, see: https://crontab.guru/#15_1_*_*_1-5
#          filters:
#            branches:
#              only:
#                - develop
#    jobs:
#      - build
  build-branch:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v.*/
  build-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
