version: 2.1

executors:
  node-executor:
    working_directory: ~/phovea
    docker:
      - image: circleci/node:14.17-buster

jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Show Node.js and npm version
          command: |
            node -v
            npm -v
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "package.json" }}
          paths: ./node_modules

      - run:
          name: Show installed npm dependencies
          command: npm list --depth=1 || true
      - run:
          name: Run test
          command: npm run test
      - persist_to_workspace:
          root: ~/phovea
          paths: .
  publish:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/phovea
      - run:
          name: Authentication
          command: |
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run:
          name: Publish package
          command: npm publish
workflows:
  version: 2.1
#  build-nightly:
#    triggers:
#      - schedule:
#          cron: "15 1 * * 1-5" # "At 01:15 on every day-of-week from Monday through Friday.”, see: https://crontab.guru/#15_1_*_*_1-5
#          filters:
#            branches:
#              only:
#                - develop
#    jobs:
#      - build
  build-branches-only:
    jobs:
      - build:
          filters:
            tags:
              ignore: /.*/
  build-publish-tag:
    jobs:
      - build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - publish:
          context:
            - org-public
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
