version: 2.1

executors:
  python-executor:
    working_directory: ~/phovea-python
    docker:
      - image: circleci/python:3.10-buster

jobs:
  python-build:
    executor: python-executor
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
      - run:
          name: Install pip requirements
          command: |
            virtualenv ~/venv
            . ~/venv/bin/activate
            make develop
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements_dev.txt" }}
          paths:
          - ~/venv
      - run:
          name: Force an update of pip dependencies from git repositories # not sure if this is working ?
          command: |
            . ~/venv/bin/activate
            pip install --upgrade --upgrade-strategy=only-if-needed -e .[develop]
      - run:
          name: Show installed pip packages
          command: |
            . ~/venv/bin/activate
            pip list || true
      - run:
          name: Linting
          command: |
            . ~/venv/bin/activate
            make lint check-format
      - run:
          name: Run tests
          command: |
            . ~/venv/bin/activate
            make test
      - run:
          name: Build wheel
          command: |
            . ~/venv/bin/activate
            make build
      - store_artifacts:
          path: dist_python
          destination: dist-python
      - persist_to_workspace:
          root: ~/.
          paths: phovea-python
  python-publish:
    executor: python-executor
    steps:
      - attach_workspace:
          at: ~/.
      - run: ls -a
      - run:
          name: Install twine
          command: |
            virtualenv ~/venv
            . ~/venv/bin/activate
            pip install twine
      - run:
          name: Authentication
          command:  |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "repository = $PYPI_REPOSITORY" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Publish package
          command: |
            . ~/venv/bin/activate
            twine upload dist_python/*
workflows:
  version: 2.1
#  build-nightly:
#    triggers:
#      - schedule:
#          cron: "15 1 * * 1-5" # "At 01:15 on every day-of-week from Monday through Friday.”, see: https://crontab.guru/#15_1_*_*_1-5
#          filters:
#            branches:
#              only:
#                - develop
#    jobs:
#      - python-build
  build-branches-only:
    jobs:
      - python-build:
          filters:
            tags:
              ignore: /.*/
  build-publish-tag:
    jobs:
      - python-build:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
      - python-publish:
          context:
              - org-public
          requires:
              - python-build
          filters:
              branches:
                ignore: /.*/
              tags:
                only: /^v.*/
