language: python

env:
  - TOXENV=py27
  - TOXENV=py34

install:
  - sudo apt-get install cython
  - pip install -r requirements_dev.txt
  - pip install -r requirements.txt

script: npm run dist

deploy:
  provider: releases
  api_key:
    secure: W+OxNzA9SX1bmBsrrJxPffPD6o/jd70qpfFHK0OVnzCCzMKXZUJS8dEr/Y/ej+Ya4zuAus1FAFIrO7yS8QeGKvRdZJkGJ9RTVUK/GKISxdLBXscDgyFl4thPguh1358fnXrZoknnUq5kaE/WRG4LkZ+GxliMMT4e0Qre8f/3QfZ+uk91NulXoytmFKpjp5XCRhfRO1zxbSvUOMjWofWcCPIOdLTJSMyQ1A4wH2T2NE7rwqI8FX6CxE/D7RC9y8r1MaFfTMCJS6RN1Wldp7qUDGfKmoDaTg93zNpaJ4HNg1fdUtPL3k4mnercWVbo8rp97hcahumbxcZ+WMEfTxvfcKTMlOkuu5Wzw0Q8RQpQMsCkOAQ/mj/lnZGl5gvvhE5dusIuAODMjuHPlXVn14sVk7H0MJW1SlFNzi5RHwa0z5qSXbI3mM27yPkgkXppr4fMnqZ8g8kgJUAyrUZQHJleI9qhf1Eb40DohT1k5UuLvfClpTe4+12YIVU0j5q9jIaGWm7vrKaxQVF6NSrQ5m30oaF1kRLpmtuO9jFKQ4HB2/ri+LuaRc5kxVezdfxjCjnP0kkYh9d48sja1MsfhL9ZP37ZmPoJ/AXXMjtKwBYw1AXKw+yl7MfMpom/EWM8k4ZwkLn/2mOIuVago+diYEXdxpHF51zQnluzEDjO0BFUBlA=
  file_glob: true
  file: dist/<%-name->*.egg
  on:
    repo: <%-githubAccount%>/<%-name%>

